 <div id="ribbon">
    <div id="page-title">
    	<h1>Rules</h1>
    </div>
    <div class="clear"></div>
  </div>
  <div id="content-wrapper">
  	<div id="content">
    <div id="single-narrow">
      <h1 align="center">December 13, 2010 Best Buy Gift Card Sweepstakes Official Rules</h1>
      <p align="center"> NO PURCHASE NECESSARY. A PURCHASE OR PAYMENT OF ANY KIND WILL NOT INCREASE YOUR CHANCES OF WINNING.   	THIS PROMOTION IS NOT AFFILIATED WITH OR ADMINISTERED BY FACEBOOK IN ANY WAY. </p>
      <h2>1. Eligibility</h2>
      <p>The December 13, 2010 Best Buy Gift Card Sweepstakes (the   &quot;Promotion&quot;) is administered by Big Prize Giveaways, LLC (&quot;BPG&quot;) and is   open to residents age 18 and older in all jurisdictions where receipt of   prizes or entry in the Promotion is not prohibited by United States   and/or local laws, rules or regulations. Prohibited countries include,   but are not limited to, Belgium, Norway, Sweden, India and residents of   any country embargoed by the United States.  Employees of BPG or any of   its respective affiliates, subsidiaries, advertising agencies,   participating sponsor or any other company involved with the design,   production, execution or distribution of the Promotion and their   immediate family (spouse, parents, siblings and children) and household   members of each such employees are not eligible. The Promotion is   subject to all applicable federal, state and local laws and regulations.   Void where prohibited. Participation constitutes entrant's (and   entrant's parent/legal guardian, if entrant is a Minor) full and   unconditional agreement to these Official Rules and BPG's decisions,   which are final and binding in all matters related to the Promotion.   Winning a prize is contingent upon fulfilling all requirements set forth   herein. The Promotion consists of a sweepstakes (the &quot;Sweepstakes&quot;).</p>
      <h2>2. Administrator</h2>
      <p>Big Prize Giveaways, LLC (PO Box 5963, Columbia, SC 29205) is the sole Administrator of the Sweepstakes.</p>
      <h2>3. Timing</h2>
      <p>The Promotion begins on December 8, 2010 at 12:00 PM Eastern Time   (&quot;ET&quot;) and ends on December 13, 2010 at 5:00 PM ET (the &quot;Promotion   Period&quot;). Administrator's computer is the official time keeping device   for this Promotion.</p>
      <h2>4. How to Enter</h2>
      <p>There are two (2) ways to enter: </p>
      <ol>
        <li>Personal Entry: You can enter the Promotion through the Big Prize   application on the Facebook Platform using the following address: <a href="http://www.bigprize.com/share/bestbuy">http://www.bigprize.com/share/bestbuy</a>.    Follow the on-screen prompts to enter. This will give you one entry   and a friend of your choice (optional) one entry. You may only submit   one Personal entry per day.</li>
        <li>Friend Entry: When one of your friends submits a Personal Entry and   lists your name as the friend of their choice, (as noted in number 1   above) that friend will receive one Personal Entry and you will receive   one Friend Entry. There is no limit to the number of valid Friend   Entries you may receive per day from this method.</li>
      </ol>
      <strong><em>General Conditions Regarding Entering:</em></strong> Entry requires   using the Big Prize application and you must become a fan of Big Prize   Giveaways' Page on Facebook to access features of the Big Prize   Giveaways Application. Use of any automated system to participate is   prohibited and may result in disqualification. Sponsor is not   responsible for lost, late, incomplete, invalid, unintelligible or   misdirected registrations, which will be disqualified. Potential winners   may be required to show proof of identity.  In the event of a dispute   as to the identity of the rightful winner, Big Prize will gather proof   of identity from the disputing parties and will solely be responsible   for choosing the winner. There is no charge for entering as free   Internet access is available at many public libraries. <strong>This   promotion is in no way sponsored, endorsed or administered by, or   associated with, Facebook. You are providing your information to Big   Prize Giveaways and not to Facebook.</strong> The information you provide will only be used to administer the promotion and in accordance with our privacy policy.
      <h2>5. Winner Selection</h2>
      <p>BPG will conduct a drawing at 5:00 pm on December 13, 2010 by   randomly selecting one Personal Entry from all Personal Entries properly   submitted during the Promotion Period. The entrant who submitted the   selected Personal Entry along with entrant listed on the corresponding   Friend Entry, if applicable, will be Potential Grand Prize Winners.</p>
      <h2>6. Verification and Notification of Potential Grand Prize Winner</h2>
      <p>ALL POTENTIAL SWEEPSTAKES WINNERS ARE SUBJECT TO VERIFICATION BY BPG   WHOSE DECISIONS ARE FINAL AND BINDING IN ALL MATTERS RELATED TO THE   PROMOTION. Potential Grand Prize Winners must continue to comply with   all terms and conditions of these Official Rules, and winning is   contingent upon fulfilling all requirements. Potential Grand Prize   Winners will be posted on the following web page: <a href="http://www.bigprize.com/winners_list">http://www.bigprize.com/winners_list</a>.   The potential winners must respond within 7 days of his/her name being   posted. In addition and as a courtesy, BPG will also attempt to alert   the Potential Grand Prize Winners using the email address provided   during the entry process, but BPG is not responsible for any technical   malfunction or undelivered email messages. IT IS YOUR RESPONSIBILITY TO   CHECK THE WEBSITE ADDRESS ABOVE AFTER THE CONCLUSION OF THIS PROMOTION   TO SEE IF YOU ARE A POTENTIAL GRAND PRIZE WINNER. Once the potential   winners have been verified to the satisfaction of BPG, BPG will arrange   for prize fulfillment. If the selected potential Grand Prize Winners are   determined to be ineligible by BPG, or fail to respond within the   required time period, the potential winners forfeit their prizes and are   disqualified. Otherwise, the selected potential Grand Prize Winners   become the Validated Grand Prize Winners. In the event that potential   Grand Prize Winners of a prize are disqualified for any reason, BPG may   in BPG’s sole discretion randomly select different winners from all   remaining eligible entries and repeat the verification process outlined   above, donate the forfeited prizes to charity or conduct a new promotion   to award the prizes.</p>
      <h2>7. Prizes</h2>
      <p>A maximum of two &quot;Grand Prizes&quot; each consisting of a $100 Best Buy   Gift Card ($100) may be awarded. Winners are responsible for all taxes   and fees associated with prize receipt and/or use. Total actual retail   value of all prizes will not exceed $200. </p>
      <h2>8. Odds of Winning</h2>
      <p>The odds of winning will depend on the number of entries. Many will enter, few will win.</p>
      <h2>9. Release</h2>
      <p>By entering this Sweepstakes, entrant agrees to release and hold   harmless Sponsor, and their respective subsidiaries, affiliates,   suppliers, distributors, advertising/promotion agencies, and each of   their respective parent companies and each such company's officers,   directors, employees and agents (collectively, the &quot;Released Parties&quot;)   from and against any claim or cause of action, including, but not   limited to, personal injury, death, or damage to or loss of property,   arising out of participation in the Promotion or receipt or use or   misuse of any prize.  Entrant also agrees to hold harmless Facebook and   their respective subsidiaries, affiliates, suppliers, distributors,   advertising/promotion agencies and Facebook’s officers, directors,   employees and agents from and against any claim or cause of action,   including, but not limited to, personal injury, death, or damage to or   loss of property, arising out of participation in the Promotion or   receipt or use or misuse of any prize.</p>
      <h2>10. Publicity</h2>
      <p>Except where prohibited, participation in the Promotion constitutes   winners consent to Sponsor's and its agents' use of winner's name,   likeness, photograph, voice, opinions, hometown and state, and/or   uploaded photo or slide show for promotional purposes in any media,   worldwide, without further payment or consideration.</p>
      <h2>11. General Conditions</h2>
      <p>Sponsor reserves the right to cancel, suspend and/or modify the   Promotion, or any part of it, if any fraud, technical failures or any   other factor beyond Sponsor's reasonable control impairs the integrity   or proper functioning of the Sweepstakes, as determined by Sponsor in   its sole discretion. Sponsor reserves the right in its sole discretion   to disqualify any individual it finds to be tampering with the entry   process or the operation of the Sweepstakes or to be acting in violation   of these Official Rules or any other promotion or in an unsportsmanlike   or disruptive manner. Any attempt by any person to deliberately   undermine the legitimate operation of the Sweepstakes may be a violation   of criminal and civil law, and, should such an attempt be made, Sponsor   reserves the right to seek damages from any such person to the fullest   extent permitted by law. Sponsor's failure to enforce any term of these   Official Rules shall not constitute a waiver of that provision.</p>
      <h2>12. Limitations of Liability</h2>
      <p>The Released Parties are not responsible for: (1) any incorrect or   inaccurate information, whether caused by entrants, printing errors or   by any of the equipment or programming associated with or utilized in   the Promotion; (2) technical failures of any kind, including, but not   limited to malfunctions, interruptions, or disconnections in phone lines   or network hardware or software; (3) unauthorized human intervention in   any part of the entry process or the Promotion; (4) technical or human   error which may occur in the administration of the Promotion or the   processing of entries; or (5) any injury or damage to persons or   property which may be caused, directly or indirectly, in whole or in   part, from entrant's participation in the Promotion or receipt or use or   misuse of any prize. If for any reason an entrant's entry is confirmed   to have been erroneously deleted, lost, or otherwise destroyed or   corrupted, entrant's sole remedy is another entry in the Sweepstakes   play, provided that if it is not possible to award another entry due to   discontinuance of the Promotion, or any part of it, for any reason,   Sponsor, at its discretion, may elect to hold a random drawing from   among all eligible entries received up to the date of discontinuance for   any or all of the prizes offered herein. No more than the stated number   of prizes will be awarded. In event that production, technical,   seeding, programming or any other reasons cause more than stated number   of prizes as set forth in these Official Rules to be available and/or   claimed, Sponsor reserves the right to award only the stated number of   prizes by a random drawing among all legitimate, unawarded, eligible   prize claims.</p>
      <h2>13. Disputes</h2>
      <p>Entrant agrees that: (i) any and all disputes, claims and causes of   action arising out of or connected with this Sweepstakes, or any prizes   awarded, other than those concerning the administration of the   Sweepstakes or the determination of winners, shall be resolved   individually, without resort to any form of class action; (ii) any and   all disputes, claims and causes of action arising out of or connected   with this Sweepstakes, or any prizes awarded, shall be resolved   exclusively by the United States District Court or the appropriate South   Carolina State Court located in Columbia, South Carolina; (iii) any and   all claims, judgments and awards shall be limited to actual   out-of-pocket costs incurred, including costs associated with entering   this Sweepstakes, but in no event attorneys' fees; and (iv) under no   circumstances will entrant be permitted to obtain awards for, and   entrant hereby waives all rights to claim punitive, incidental and   consequential damages and any other damages, other than for actual   out-of-pocket expenses , and any and all rights to have damages   multiplied or otherwise increased. SOME JURISDICTIONS DO NOT ALLOW THE   LIMITATIONS OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL   DAMAGES, SO THE ABOVE MAY NOT APPLY TO YOU. All issues and questions   concerning the construction, validity, interpretation and enforceability   of these Official Rules, or the rights and obligations of the entrant   and Sponsor in connection with the Promotion, shall be governed by, and   construed in accordance with, the laws of the State of South Carolina,   without giving effect to any choice of law or conflict of law rules   (whether of the State of South Carolina or any other jurisdiction),   which would cause the application of the laws of any jurisdiction other   than the State of South Carolina.</p>
      <h2>14. Entrant's Personal Information</h2>
      <p>Information collected from entrants is subject to the Big Prize Giveaways Privacy Policy, which is available at <a href="http://www.bigprize.com/privacy">http://www.bigprize.com/privacy</a>.</p>
      <h2>15. Promotion Results</h2>
      <p>For Promotion results and/or a copy of these Official Rules, send a   hand-printed, self-addressed, stamped envelope to $100 Best Buy Gift   Card Sweepstakes, c/o Big Prize Giveaways, LLC, PO Box 5963, Columbia,   SC 29205. Requests for the winners list must be received by December 31,   2010. VT residents may exclude return postage.</p>
    </div>
  </div>
</div><!-- // content-wrapper -->